FROM python:3.7-buster

COPY ./python_packages /python_packages


WORKDIR /python_packages
RUN pip download prometheus_client
#RUN pip download confluent-kafka

#RUN pip install /python_packages/*
WORKDIR /
COPY ./app /app

ENTRYPOINT ["tail","-f","dev/null"]

